### ISSUE TITLE
Small bug sometime

### ISSUE THREAD

**Issue by mikhoul** [Noitidart/GlobalFindbar#10]
I experience a small annoying bug from time to time, the add-on seem to disable itself. 

I use it mainly cause I search for a term in many tabs and sometime I change to find a term to another tab and the "find bar" don't follow.  :astonished:

When it happen to resolve the problem I need to reinstall the add-on and everything is fine again till the next time it happen.

I'm on Firefox 44 latest under Win 7 .  

Regards :blush:

**Comment by Noitidart** [comment]
Hi there mikhoul thanks very much for your report.

I haven't updated this addon in a long time.

This addon is far outdone by the excellent FindBar Tweak addon by @Quicksaver - which I use myself now. You should check that one out. If that doesn't meet your standards though, let me know please and I'll try to update this addon sometime soon.

I'm busy right now with Profilist, NativeShot, MouseControl, (and maybe) FoxSpeak. :)

**Comment by mikhoul** [comment]
Thanks for the hint ! 

I tried _FindBar Tweak addon_ today and it's perfect !   👍👍👍

**Comment by Noitidart** [comment]
I put a note in my addon description recommending popel to use FindBar Tweak :)

![](http://i.imgur.com/ktpAoLe.png)
